[theme]
primaryColor = "#4A90E2"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7FA"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
enableCORS = false

[client]
showSidebarNavigation = false
toolbarMode = "default"

